import { z } from "zod";

export interface ITripStructure {
  destination: string;
  description: string;
  abbreviation: string;
  // tripNodes: ITripNodeStructure[];
}

export interface ITripNodeStructure {
  destination: string;
  description: string;
  date: Date;
}

export class StructureService {
  /**
   * Creates a Zod schema for validating trip data structure.
   * Defines the expected format for trip objects generated by AI.
   */
  tripStructure() {
    return z.object({
      destination: z.string().min(1).max(250).describe("Primary location of the trip"),
      description: z.string().min(1).max(800).describe("Short description of the trip"),
      abbreviation: z.string().min(1).max(5).describe("Abbreviation for the trip based on destination"),
      // tripNodes: z.array(await this.tripNodeStructure()).min(1),
    });
  }

  /**
   * Creates a Zod schema for validating trip node data structure.
   * Defines the expected format for individual trip node objects within a trip.
   */
  tripNodeStructure() {
    return z.object({
      destination: z.string().min(1).max(250).describe("Location of the trip node"),
      description: z
        .string()
        .min(1)
        .max(2500)
        .describe("Detailed description of activities or events at this trip node"),
      date: z.date().describe("Date when this trip node occurs"),
    });
  }
}
