name: Mean UI CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  build_and_deploy_stage:
    runs-on: ubuntu-latest
    name: Build and Deploy to Staging
    environment: Staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy to Staging
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_ORANGE_GLACIER_050C76B1E }}
          action: "upload"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./ui" # App source code path
          api_location: "" # Api source code path - optional
          app_build_command: npm run build:stage
          output_location: "dist/ui/browser" # Built app content directory
          deployment_environment: "staging" # Environment name for deployment

  build_and_deploy_prod:
    runs-on: ubuntu-latest
    name: Build and Deploy to Production
    environment: Production
    needs: build_and_deploy_stage

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy to Production
        id: builddeployprod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_ORANGE_GLACIER_050C76B1E }}
          action: "upload"
          app_location: "./ui"
          api_location: ""
          app_build_command: npm run build:prod
          output_location: "dist/ui/browser"
